server:
  port: 8082

spring:
  application:
    name: wallet-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/walletdb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,circuitbreakers
  endpoint:
    health:
      show-details: always
